import UUID from "./UUID";
import { Player } from "./response/PlayerResponse";
import { Guild } from "./response/GuildResponse";
import { Booster } from "./response/BoostersResponse";
import { Leaderboards } from "./response/LeaderboardsResponse";
import { KeyInfo } from "./response/KeyResponse";
export declare function getPlayerByUuid(uuid: UUID, apiKey: UUID): Promise<Player>;
export declare function getPlayerByName(name: string, apiKey: UUID): Promise<Player>;
export declare function findGuildIdByPlayerName(name: string, apiKey: UUID): Promise<string>;
export declare function findGuildIdByPlayerUuid(uuid: UUID, apiKey: UUID): Promise<string>;
export declare function getGuildById(id: string, apiKey: UUID): Promise<Guild>;
export declare function getGuildByPlayerName(name: string, apiKey: UUID): Promise<Guild>;
export declare function getGuildByPlayerUuid(uuid: UUID, apiKey: UUID): Promise<Guild>;
export declare function getBoosters(apiKey: UUID): Promise<Booster[]>;
export declare function getBoostersIsDecrementing(apiKey: UUID): Promise<boolean>;
export declare function getLeaderboards(apiKey: UUID): Promise<Leaderboards>;
export declare function getKey(apiKey: UUID): Promise<KeyInfo>;
